import wx

""" Custom widgets referenced in the code generated by wxFB """

class MenuButton(wx.Button):
    def __init__(self, parent, id=wx.ID_ANY, label='', pos=wx.DefaultPosition, size=wx.DefaultSize, style=0, validator=wx.DefaultValidator, name=wx.ButtonNameStr):
        super().__init__(parent=parent, id=id, label=label, pos=pos, size=size, style=style, validator=validator, name=name)
        self.menu = None
        self.menu_update_callback = None
        self.parent = parent
        self.Bind(wx.EVT_BUTTON, self.on_show_menu)

    def set_menu_config(self, menu=None, menu_update_callback=None):
        self.menu = menu
        self.menu_update_callback = menu_update_callback

    def on_show_menu(self, event):
        if self.menu is not None:
            if self.menu_update_callback is not None:
                self.menu_update_callback(self.menu)
            btn_size = self.GetSize()
            self.PopupMenu(self.menu, (0, btn_size.y))
        event.Skip()

class PcbItemListBox(wx.ListBox):
    def __init__(self, parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, choices=[], style=0, validator=wx.DefaultValidator, name=''):
        super().__init__(parent=parent, id=id, pos=pos, size=size, choices=choices, style=style, validator=validator, name=name)
        self.select_handler = None
        self.uuids = []
        self.Bind(wx.EVT_LISTBOX, self.on_item_selected)

    def set_item_list(self, item_list):
        self.uuids = []
        self.Clear()
        for item in item_list:
            self.uuids.append(item[0])
            self.Append(item[2])

    def set_select_handler(self, handler):
        self.select_handler = handler

    def on_item_selected(self, event):
        if self.select_handler is not None:
            self.select_handler(self.uuids[self.GetSelection()])
        event.Skip()
